import { mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import type { BuildIntent } from "@agentos/shared";

export function resolveOutputDir(missionId: string) {
  const base = process.env.AGENTOS_OUTPUT_DIR?.trim() || join(homedir(), ".agentos", "outputs");
  return join(base, missionId);
}

export type ScaffoldResult = {
  outputDir: string;
  files: string[];
  previewReadme: string;
};

export function scaffoldApp(intent: BuildIntent, missionId: string): ScaffoldResult {
  const outputDir = resolveOutputDir(missionId);
  mkdirSync(outputDir, { recursive: true });

  const appSlug = intent.appName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "generated-app";
  const files: string[] = [];

  const write = (relativePath: string, content: string) => {
    const fullPath = join(outputDir, relativePath);
    mkdirSync(join(fullPath, ".."), { recursive: true });
    writeFileSync(fullPath, content, "utf8");
    files.push(relativePath);
  };

  write(
    "package.json",
    JSON.stringify(
      {
        name: appSlug,
        private: true,
        version: "0.1.0",
        scripts: { dev: "next dev", build: "next build", start: "next start" }
      },
      null,
      2
    )
  );

  write(
    "app/page.tsx",
    `"use client";

export default function GeneratedAppPage() {
  return (
    <main style={{ fontFamily: "system-ui", padding: "2rem", maxWidth: 720 }}>
      <h1>${intent.appName}</h1>
      <p>${intent.summary.slice(0, 280).replace(/"/g, "'")}</p>
      <section>
        <h2>Preferences</h2>
        <ul>
          ${Object.entries(intent.answers ?? {})
            .map(([key, value]) => `<li><strong>${key}:</strong> ${String(value).replace(/</g, "")}</li>`)
            .join("\n          ") || "<li>No questionnaire answers yet.</li>"}
        </ul>
      </section>
      <button type="button" onClick={() => typeof speechSynthesis !== "undefined" && speechSynthesis.speak(new SpeechSynthesisUtterance(document.querySelector("p")?.textContent ?? ""))}>
        Read aloud
      </button>
    </main>
  );
}
`
  );

  write(
    "README.md",
    `# ${intent.appName}

Generated by AgentOS for mission \`${missionId}\`.

## Summary
${intent.summary}

## Develop
\`\`\`bash
pnpm install
pnpm dev
\`\`\`
`
  );

  return {
    outputDir,
    files,
    previewReadme: `Scaffolded ${files.length} files at ${outputDir}`
  };
}
