export const panelChromeClassName = "forge-panel";

export * from "./adapters/types";
export * from "./motion";
export { AppShell } from "./components/AppShell";
export { TopNav } from "./components/TopNav";
export { TerminalWindow } from "./components/TerminalWindow";
export { MissionControlPanel } from "./components/MissionControlPanel";
export { AgentActivityFeed } from "./components/AgentActivityFeed";
export { CommandInput } from "./components/CommandInput";
export { StatusRail } from "./components/StatusRail";
export { MetricPill } from "./components/MetricPill";
export { QuickActionButton } from "./components/QuickActionButton";
export { ApprovalCard } from "./components/ApprovalCard";
export { IntegrationCard } from "./components/IntegrationCard";
export { GeneratedAppFrame } from "./components/GeneratedAppFrame";
export { MissionTimeline } from "./components/MissionTimeline";
export { AgentPresenceCard } from "./components/AgentPresenceCard";
export { AgentRichMessageCard } from "./components/AgentRichMessageCard";
export { SandboxApprovalCenter } from "./components/SandboxApprovalCenter";
export { ReactiveWorkbenchPanel } from "./components/ReactiveWorkbenchPanel";
export { AmbientSystemHealthBar } from "./components/AmbientSystemHealthBar";
export { CommandPalette } from "./components/CommandPalette";
export { ForgeSectionHeader } from "./components/ForgeSectionHeader";
export { ForgeStatCard } from "./components/ForgeStatCard";
export { ForgeSegmentedControl } from "./components/ForgeSegmentedControl";
export { ForgeFaqAccordion } from "./components/ForgeFaqAccordion";
export type { ForgeFaqItem } from "./components/ForgeFaqAccordion";
