param(
    [string]$Model = "qwen2.5-coder:7b"
)

$ErrorActionPreference = "Stop"

$ProjectRoot = "$env:USERPROFILE\Documents\AgenOS"
Set-Location $ProjectRoot

$OutputPath = ".\docs\LOCAL_AI_REVIEW.md"

$FilesToRead = @(
    "README.md",
    "AGENTS.md",
    "package.json",
    "pnpm-workspace.yaml",
    "apps/command-center/src/app/layout.tsx",
    "apps/command-center/src/app/page.tsx",
    "packages/shared/src/index.ts",
    "apps/api/src/index.ts",
    "apps/api/src/store.ts"
)

$ContextBlocks = New-Object System.Collections.Generic.List[string]

foreach ($file in $FilesToRead) {
    if (Test-Path $file) {
        $content = Get-Content $file -Raw
        if ($content.Length -gt 12000) {
            $content = $content.Substring(0, 12000) + "`n...[truncated]..."
        }

        $ContextBlocks.Add("`n--- FILE: $file ---`n$content")
    }
}

$RepoContext = $ContextBlocks -join "`n"

$Prompt = @"
You are a local read-only coding reviewer for the AgentOS MVP.

The project is a working local pnpm monorepo with:
- Next.js command center frontend
- Fastify mock API
- Allow-listed gateway
- Local worker
- Shared packages for agents, memory, token budget, persistence, and UI

Rules:
- DO NOT suggest huge rewrites.
- DO NOT suggest auth, Discord, real databases, Docker changes, or production deployment yet.
- DO NOT output code patches.
- DO NOT tell me to edit files automatically.
- Focus on the next 10 tiny improvements that are safe while Codex tokens recharge.
- Each task should touch 1-3 files max.
- Prefer mission-flow polish, dashboard clarity, developer experience, runtime safety, and tests.
- Include a "Best next Codex prompt" section at the end.
- Include a "Safe to do manually" section.
- Include a "Do not do yet" section.

Repo context:
$RepoContext
"@

Write-Host "Sending read-only review request to Ollama model: $Model"
Write-Host "This may take several minutes..."

$Body = @{
    model = $Model
    prompt = $Prompt
    stream = $false
    options = @{
        temperature = 0.2
        num_ctx = 8192
    }
} | ConvertTo-Json -Depth 10

$Response = Invoke-RestMethod `
    -Uri "http://127.0.0.1:11434/api/generate" `
    -Method Post `
    -ContentType "application/json" `
    -Body $Body `
    -TimeoutSec 3600

$Header = @"
# AgentOS Local AI Review

Generated by Ollama model: $Model

This is a read-only review. It did not modify project source files.

"@

$Header + $Response.response | Set-Content $OutputPath -Encoding UTF8

Write-Host "Review written to:"
Write-Host $OutputPath
